import '@/app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/app/components/ui/navbar'
import ThemeProviders from "@/app/components/themeProviders"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body suppressHydrationWarning={true} className={`${inter.className} dark:bg-gray-700`}>
          <ThemeProviders attribute='class'>
            <main className="w-[700px] px-3 py-5 md:px-5 min-h-screen">
              <Navbar/>
              {children}
            </main>
          </ThemeProviders>
        </body>
    </html>
  )
}
